import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='container mx-auto mt-20 flex max-w-[750px] flex-col gap-y-6 px-2'>{children}</div>
      </body>
    </html>
  );
}
